apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-svc
  namespace: default
  labels:
    app: gitops-demo
spec:
  selector:
    app: gitops-demo
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer       # Use ClusterIP + Ingress in production
